a = "  !!Ram!!! !!!   "
print(len(a))
print(a)
print(a.upper())
print(a.lower())
print(a.rstrip("!"))
print(a.replace("Ram", "krishna"))
print(a.split(" "))
b = "introduction yourselF"
print(b.capitalize())
print(b.center(30))
print(a.count("Ram"))
print(a.endswith("!"))
print(b.endswith("on", 2,12))
print(b.startswith("on"))
print(b.find("on"))
print(b.index(("on")))
str1 = "welcome009"
print(str1.isalnum())
print(str1.isalpha())
str2 = "rdx\n"
print(str2.isprintable())
print(str2.isspace())
print(str2.istitle())
print(b.swapcase())
print(b.title())
